Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
Data = pd.read_csv("DataSet/Churn_Modelling.csv")
Data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
Data.shape

(10000, 14)

In [4]:
X = Data.iloc[:,3:13].values
(pd.DataFrame(X)).head(10)

0        1       2   3  4        5  6  7  8        9
0  619   France  Female  42  2        0  1  1  1   101349
1  608    Spain  Female  41  1  83807.9  1  0  1   112543
2  502   France  Female  42  8   159661  3  1  0   113932
3  699   France  Female  39  1        0  2  0  0  93826.6
4  850    Spain  Female  43  2   125511  1  1  1  79084.1
5  645    Spain    Male  44  8   113756  2  1  0   149757
6  822   France    Male  50  7        0  2  1  1  10062.8
7  376  Germany  Female  29  4   115047  4  1  0   119347
8  501   France    Male  44  4   142051  2  0  1  74940.5
9  684   France    Male  27  2   134604  1  1  1  71725.7

In [5]:
Y = Data.iloc[:,13].values
(pd.DataFrame(Y)).head(10)

0
0  1
1  0
2  1
3  0
4  0
5  1
6  0
7  1
8  0
9  0

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
labelencoder_x1 = LabelEncoder()
X[:,1] = labelencoder_x1.fit_transform(X[:,1])

LabelEncoder_x2 = LabelEncoder()
X[:,2] = LabelEncoder_x2.fit_transform(X[:,2])

In [8]:
pd.DataFrame(X[:,1]).head()

0
0  0
1  2
2  0
3  0
4  2

In [9]:
pd.DataFrame(X[:,2]).head()

0
0  0
1  0
2  0
3  0
4  0

In [10]:
(pd.DataFrame(X)).head()

0  1  2   3  4        5  6  7  8        9
0  619  0  0  42  2        0  1  1  1   101349
1  608  2  0  41  1  83807.9  1  0  1   112543
2  502  0  0  42  8   159661  3  1  0   113932
3  699  0  0  39  1        0  2  0  0  93826.6
4  850  2  0  43  2   125511  1  1  1  79084.1

In [12]:
OneHotEncoder = OneHotEncoder(categorical_features=[1])
X = OneHotEncoder.fit_transform(X).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [14]:
X=X[:,1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_tr,X_ts,Y_tr,Y_ts = train_test_split(X,Y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc_x = StandardScaler()
X_tr = sc_x.fit_transform(X_tr)
X_ts = sc_x.transform(X_ts)

In [19]:
(pd.DataFrame(X_tr)).head()

0         1         2         3         4         5         6   \
0 -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717   
1  1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2 -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3 -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4 -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   

         7         8         9         10  
0  0.809503  0.642595 -1.032270  1.106432  
1 -0.921591  0.642595  0.968738 -0.748664  
2 -0.921591  0.642595 -1.032270  1.485335  
3 -0.921591  0.642595 -1.032270  1.276528  
4  0.809503  0.642595  0.968738  0.558378

In [20]:
(pd.DataFrame(X_ts)).head()

0         1         2         3         4         5         6   \
0  1.754865 -0.573694 -0.552043 -1.091687 -0.368904  1.044737  0.879303   
1 -0.569844 -0.573694 -1.314903 -1.091687  0.109617 -1.031415  0.429722   
2 -0.569844  1.743090  0.571630 -1.091687  0.301026  1.044737  0.308583   
3 -0.569844 -0.573694  1.416961  0.916013 -0.656016 -0.339364  0.575336   
4  1.754865 -0.573694  0.571630  0.916013 -0.081791  0.006661  1.389611   

         7         8         9         10  
0 -0.921591  0.642595  0.968738  1.610857  
1 -0.921591  0.642595 -1.032270  0.495870  
2 -0.921591  0.642595  0.968738 -0.424787  
3 -0.921591 -1.556190 -1.032270 -0.187777  
4  0.809503  0.642595  0.968738  0.616842

In [24]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [26]:
Classifier = Sequential()
Classifier.add(Dense(units=6, kernel_initializer="uniform", activation="relu",input_dim=11))


In [27]:
#units=n es el num de neuronas
Classifier.add(Dense(units=6, kernel_initializer="uniform", activation="relu"))

In [28]:
Classifier.add(Dense(units=1, kernel_initializer="uniform", activation="sigmoid"))

In [30]:
Classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [31]:
Classifier.fit(X_tr,Y_tr,batch_size=10,epochs=100)
#batch size es el tamaño de bloque el cual agarra

Epoch 1/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4865 - accuracy: 0.7950
Epoch 2/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4277 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4221 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4184 - accuracy: 0.8224
Epoch 5/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4160 - accuracy: 0.8279
Epoch 6/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4137 - accuracy: 0.8304
Epoch 7/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4126 - accuracy: 0.8325
Epoch 8/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4107 - accuracy: 0.8336
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4101 - accuracy: 0.8335
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 115us/step - loss: 0.4005 - accuracy: 0.8341
Epoch 79/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4003 - accuracy: 0.8349
Epoch 80/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4005 - accuracy: 0.8349
Epoch 81/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4004 - accuracy: 0.8345
Epoch 82/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4007 - accuracy: 0.8356
Epoch 83/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4003 - accuracy: 0.8340
Epoch 84/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4005 - accuracy: 0.8349
Epoch 85/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4001 - accuracy: 0.8351
Epoch 86/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4002 - accuracy: 0.8342
Epoch 87/100
8000/8000 [==============================] - 1

In [33]:
Y_pr = Classifier.predict(X_ts)
Y_pr

array([[0.14497969],
       [0.28746897],
       [0.1544641 ],
       ...,
       [0.14968592],
       [0.13187695],
       [0.06882253]], dtype=float32)

In [35]:
Y_pr = (Y_pr > 0.5)
pd.DataFrame(Y_pr) 

0
0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
...     ...
1970  False
1971  False
1972  False
1973  False
1974  False
1975  False
1976  False
1977  False
1978  False
1979  False
1980  False
1981  False
1982  False
1983  False
1984  False
1985  False
1986  False
1987  False
1988  False
1989  False
1990  False
1991  False
1992  False
1993  False
1994  False
1995  False
1996  False
1997  False
1998  False
1999  False

[2000 rows x 1 columns]

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
cm = confusion_matrix(Y_pr,Y_ts)
cm

array([[1561,  287],
       [  34,  118]], dtype=int64)